### ISSUE TITLE
Normalizing gene signatures

### ISSUE THREAD

**Issue by lima1** [jfnavarro/st_viewer#37]
Hi, 

I have some trouble visualizing gene signatures. Without normalization, some of the more subtle differences are obviously lost due to differences in total transcripts per spot. If I turn on normalization, it seems like the normalization uses only on the selected genes, not all, right? 

What are the best practices to visualize heatmaps of signatures?

As a related note, I tried to calculate these heatmaps in R with Seurat and generating a spot color file, but it seems like hex color codes are not supported. Would be a nice and useful addition.

I'm still using 0.7.0, so apologies in advance if some of this is changed in newer versions.

Thanks,
Markus

**Comment by jfnavarro** [comment]
I am sorry I completely missed this.

**Comment by lima1** [comment]
No worries! Seurat is now supporting spatial data as you know, so I'm all set.
